using System.Net;
using System.Text.RegularExpressions;
using FluentAssertions;
using TestIT.ApiTests.Helpers;
using TestIT.ApiTests.Models;
using Xunit;
using Xunit.Abstractions;

namespace TestIT.ApiTests.Tests;

/// <summary>
/// Verifies slug generation invariants and immutability contracts:
///   - Auto-generated slugs are URL-safe (lowercase, no spaces or unsafe chars)
///   - Slugs are immutable: a PATCH that includes a slug field is ignored or rejected
///   - Updating a test's title via PATCH does not change its slug
///   - A test remains accessible under its original slug after a title change
/// </summary>
public class SlugBehaviorTests : IDisposable
{
    private readonly ApiClient _apiClient;

    public SlugBehaviorTests(ITestOutputHelper output)
    {
        ApiClient.SetOutput(output.WriteLine);
        _apiClient = new ApiClient(TestConfiguration.GetBaseUrl());
    }

    [Fact]
    [Trait("Category", "Functional")]
    [Trait("Priority", "P1")]
    public async Task Slug_AutoGenerated_IsUrlSafe()
    {
        // Arrange: title with spaces and mixed case
        await TestDataHelper.RegisterAndLoginAsync(_apiClient);
        var test = await TestDataHelper.CreateTestAsync(_apiClient,
            "My Test Title With Spaces And CAPS");

        // Assert: slug must be URL-safe — only lowercase letters, digits, and hyphens
        test.Slug.Should().NotBeNullOrEmpty("slug must be generated");
        test.Slug.Should().MatchRegex(@"^[a-z0-9\-]+$",
            $"slug '{test.Slug}' must contain only lowercase letters, digits, and hyphens " +
            "(no spaces, uppercase, or special characters)");
    }

    [Fact]
    [Trait("Category", "Functional")]
    [Trait("Priority", "P1")]
    public async Task Slug_IsImmutable_PatchAttemptIsIgnoredOrRejected()
    {
        // Arrange
        await TestDataHelper.RegisterAndLoginAsync(_apiClient);
        var test = await TestDataHelper.CreateTestAsync(_apiClient,
            $"ImmutableSlug_{Guid.NewGuid().ToString("N")[..8]}");
        string originalSlug = test.Slug;

        // Act: try to PATCH the slug field to a new value
        var patchResp = await _apiClient.PatchAsync($"tests/{test.Slug}/",
            new { slug = "my-hacked-slug", title = test.Title });
        var body = await patchResp.Content.ReadAsStringAsync();

        // Assert: slug must be unchanged regardless of whether the PATCH succeeded or rejected slug
        // A 200 is acceptable if the API silently ignores the slug field;
        // a 400 is acceptable if the API explicitly rejects slug changes.
        patchResp.StatusCode.Should().BeOneOf(
            new[] { HttpStatusCode.OK, HttpStatusCode.BadRequest },
            $"PATCH with a slug field must be accepted-and-ignored or rejected, not cause a 5xx. Body: {body[..Math.Min(200, body.Length)]}");

        // Fetch the test and confirm the slug is still the original
        var fetched = await _apiClient.GetAsync<TestResponse>($"tests/{originalSlug}/");
        fetched.Should().NotBeNull(
            $"the test must still be accessible at its original slug '{originalSlug}'");
        fetched!.Slug.Should().Be(originalSlug,
            "the slug must not have changed — slugs are immutable");
    }

    [Fact]
    [Trait("Category", "Functional")]
    [Trait("Priority", "P1")]
    public async Task Slug_DoesNotChangeWhenTitleIsUpdated()
    {
        // Arrange
        await TestDataHelper.RegisterAndLoginAsync(_apiClient);
        var test = await TestDataHelper.CreateTestAsync(_apiClient,
            $"OriginalTitle_{Guid.NewGuid().ToString("N")[..8]}");
        string originalSlug = test.Slug;

        // Act: PATCH only the title
        var patchResp = await _apiClient.PatchAsync($"tests/{test.Slug}/",
            new { title = "Completely New Title For This Test" });
        patchResp.StatusCode.Should().Be(HttpStatusCode.OK, "title update must succeed");

        // Assert: slug must be unchanged
        var updated = await _apiClient.DeserializeResponseAsync<TestResponse>(patchResp);
        updated!.Slug.Should().Be(originalSlug,
            "updating the title must not regenerate or change the slug");
        updated.Title.Should().Be("Completely New Title For This Test",
            "the new title must be persisted");
    }

    [Fact]
    [Trait("Category", "Functional")]
    [Trait("Priority", "P1")]
    public async Task Test_RemainsAccessibleByOriginalSlug_AfterTitleChange()
    {
        // Arrange
        await TestDataHelper.RegisterAndLoginAsync(_apiClient);
        var test = await TestDataHelper.CreateTestAsync(_apiClient,
            $"AccessSlug_{Guid.NewGuid().ToString("N")[..8]}");
        string originalSlug = test.Slug;

        // Update the title
        await _apiClient.PatchAsync($"tests/{test.Slug}/",
            new { title = "Title Changed But Slug Same" });

        // Act: fetch using the original slug
        var fetched = await _apiClient.GetAsync<TestResponse>($"tests/{originalSlug}/");

        // Assert
        fetched.Should().NotBeNull(
            $"test must still be accessible at slug '{originalSlug}' after a title change");
        fetched!.Title.Should().Be("Title Changed But Slug Same",
            "the updated title must be returned when accessing via the original slug");
    }

    [Fact]
    [Trait("Category", "Functional")]
    [Trait("Priority", "P2")]
    public async Task Slug_GeneratedFromSpecialCharTitle_IsUrlSafe()
    {
        // Arrange: title with accents, punctuation, and emoji
        await TestDataHelper.RegisterAndLoginAsync(_apiClient);
        var test = await TestDataHelper.CreateTestAsync(_apiClient,
            "C# & Python: a résumé test! (2026)");

        // Assert: even from a special-char title the slug must be URL-safe
        test.Slug.Should().NotBeNullOrEmpty("a slug must be generated even from special-char titles");
        test.Slug.Should().MatchRegex(@"^[a-z0-9\-]+$",
            $"slug '{test.Slug}' must be URL-safe even when derived from a title with special characters");
    }

    public void Dispose() => _apiClient?.Dispose();
}
